#https://www.saasbase.dev/dockerfile-for-react-and-typescript/
#https://cloudnweb.dev/2019/09/building-a-production-ready-node-js-app-with-typescript-and-docker/
FROM node:17-alpine as node

FROM node AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

copy . .

RUN npm run build

#Stage 2
FROM node AS final

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i --only=production

COPY --from=builder /usr/src/app/dist ./dist

COPY --from=builder /usr/src/app/.env ./

EXPOSE ${PORT}

CMD ["node", "./dist/app.js"]