#https://www.saasbase.dev/dockerfile-for-react-and-typescript/
FROM node:18.3.0-buster
WORKDIR /usr/src/app
COPY /server/package*.json ./
RUN npm install
COPY /server/. .
RUN npm i
EXPOSE ${PORT}
CMD [ "npm", "run", "dev" ]