#https://www.saasbase.dev/dockerfile-for-react-and-typescript/
FROM node:17.9.0-buster
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm i
EXPOSE ${PORT}
CMD [ "npm", "run", "dev" ]