kind: Namespace
apiVersion: v1
metadata:
  name: stutor
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: stutor
    name: stutor-deployment
    namespace: stutor
spec:
    replicas: 1
    selector:
        matchLabels:
            app: stutor
    template:
        metadata:
            labels:
                app: stutor
        spec:
            containers:
            - image: ghcr.io/tobiass1402/stutorserver-prod:master
              imagePullPolicy: Always
              name: stutor
              ports:
                - containerPort: 3000
              env:
                - name: SECRET
                  valueFrom:
                    secretKeyRef:
                      name: stutorsecrets
                      key: API_SECRET
                - name: JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: stutorsecrets
                      key: JWT_SECRET
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: stutorsecrets
                      key: DATABASE_URL
                - name: JWT_ALGO
                  value: HS256
                - name: CLIENT_ID
                  value: api.stutor.me
                - name: BASE_URL
                  value: https://stutor.seijsener.space
                - name: OPENAPI_SCHEME
                  value: https
                - name: OPENAPI_HOST
                  value: stutor.seijsener.space
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: stutorsecrets
  namespace: stutor
type: Opaque
data:
  API_SECRET: #BASE64 encoded
  JWT_SECRET: #BASE64 encoded
  DATABASE_URL: #BASE64 encode
  POSTGRES_PASSWORD:  #BASE64 encode
---
apiVersion: v1
kind: Service
metadata:
  name: stutor-service
  namespace: stutor
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: stutor
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stutor-ingress
  namespace: stutor
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - stutor.seijsener.space
    secretName: tls-secret
  rules:
  - host: stutor.seijsener.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stutor-service
            port:
              number: 3000
---
apiVersion: cert-manager.io/v1 #https://devopstales.github.io/cloud/aks-ingress-controller/
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: stutor
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acme@seijsener.space
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
--- 
apiVersion: v1 #https://docs.microsoft.com/nl-nl/azure/aks/azure-disks-dynamic-pv
kind: PersistentVolumeClaim
metadata:
  name: stutor-pvc
  namespace: stutor
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stutor-db
  namespace: stutor
spec:
  replicas: 1
  serviceName: stutor-db-service
  selector:
    matchLabels:
      app: stutor-db
  template:
    metadata:
      labels:
        app: stutor-db
    spec:
      containers:
      - image: postgres:14-alpine
        name: stutor-db
        volumeMounts:
          - name: postgres-claim
            mountPath: /var/lib/postgresql/data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: "stutor"
        - name: POSTGRES_USER
          value: "stutoradmin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stutorsecrets
              key: POSTGRES_PASSWORD
        - name: TZ
          value: "Europe/Amsterdam"
        - name: PGDATA
          value: "/var/lib/postgresql/data/stutor-db"
      volumes:
        - name: postgres-claim
          persistentVolumeClaim:
            claimName: stutor-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stutor-db-service
  namespace: stutor
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: stutor-db