#https://www.saasbase.dev/dockerfile-for-react-and-typescript/
FROM node:17.8-buster
WORKDIR /usr/src/app
COPY /source/server/package*.json ./
RUN npm install
COPY /source/server/. .
RUN npm i
EXPOSE ${PORT}
CMD [ "npm", "run", "dev" ]
